export const initialState = {
  isLogin: false,
  genderToggle: 1,
  curLocation: { lat: '', lon: '' },
  userInfo: {},
  weatherFilter: '',
  mapPage: false,
  curRoom: null,
  searchWord: '',
  selectWord: '',
  editPassword: false,
  item: [],
  postInfo: {},
  readPostId: '',
  homePost: [],
}
